[package]
name = "tdigest"
version = "0.1.0"
authors = ["Aditya Mukerjee <dev@chimeracoder.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rand = "0.7.3"
