version: '2.1'

jobs:
  build:
    docker:
      - image: cimg/rust:1.62.0
    steps:
      - checkout
      - run: cargo --version
      - run:
          name: Build all
          command: "cargo build --all-targets"
      - run:
          name: Run Tests
          command: "cargo test"

